# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 16:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u4e66\u540d')),
                ('price', models.FloatField(default=0, verbose_name='\u4ef7\u683c')),
                ('author', models.CharField(max_length=128, verbose_name='\u4f5c\u8005')),
                ('publish_date', models.DateField(default=datetime.datetime.now, verbose_name='\u4e0a\u67b6\u65f6\u95f4')),
                ('image', models.ImageField(max_length=50, upload_to='books/%Y/%m', verbose_name='\u5c01\u9762\u56fe')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u56fe\u4e66',
                'verbose_name_plural': '\u56fe\u4e66',
            },
        ),
        migrations.CreateModel(
            name='BookDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u7c7b\u522b')),
            ],
            options={
                'verbose_name': '\u7c7b\u522b',
                'verbose_name_plural': '\u7c7b\u522b',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.BookDict', verbose_name='\u56fe\u4e66\u7c7b\u522b'),
        ),
    ]
