# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170310_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.TextField(blank=True, default='\u6682\u65e0\u4ecb\u7ecd', null=True, verbose_name='\u8be6\u7ec6\u4ecb\u7ecd'),
        ),
    ]
