# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_borrowlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowlist',
            name='book_name',
            field=models.CharField(max_length=128, verbose_name='\u56fe\u4e66\u540d'),
        ),
        migrations.AlterField(
            model_name='borrowlist',
            name='borrow_user',
            field=models.CharField(max_length=128, verbose_name='\u501f\u9605\u4eba'),
        ),
    ]
