# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20170313_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowlist',
            name='return_book',
            field=models.CharField(choices=[('ygh', '\u5df2\u5f52\u8fd8'), ('wgh', '\u672a\u5f52\u8fd8')], default='\u672a\u5f52\u8fd8', max_length=10, verbose_name='\u662f\u5426\u5f52\u8fd8'),
        ),
    ]
