# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_borrowlist_return_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowlist',
            name='return_date',
            field=models.DateField(blank=True, default=None, verbose_name='\u501f\u9605\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='borrowlist',
            name='return_book',
            field=models.CharField(choices=[('wgh', '\u672a\u5f52\u8fd8'), ('ygh', '\u5df2\u5f52\u8fd8')], default='\u672a\u5f52\u8fd8', max_length=10, verbose_name='\u662f\u5426\u5f52\u8fd8'),
        ),
    ]
