# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20170319_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowlist',
            name='return_book',
            field=models.CharField(choices=[('wgh', '\u672a\u5f52\u8fd8'), ('ygh', '\u5df2\u5f52\u8fd8')], default='wgh', max_length=10, verbose_name='\u662f\u5426\u5f52\u8fd8'),
        ),
    ]
